# Generated by Django 4.2.2 on 2023-06-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interacao', '0004_alter_interacao_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacao',
            name='case',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='interacao',
            name='ordem',
            field=models.IntegerField(),
        ),
    ]
