# Generated by Django 4.2.2 on 2023-06-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interacao', '0006_alter_interacao_ordem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interacao',
            name='case',
        ),
    ]
