# Generated by Django 4.2.2 on 2023-06-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_usertoken_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='password_simplejwt',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='username_simplejwt',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
