# Generated by Django 4.2.2 on 2023-06-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=10)),
            ],
        ),
    ]
