# Generated by Django 4.2.2 on 2023-06-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='bot',
            field=models.BooleanField(default=True),
        ),
    ]
