# Generated by Django 4.2.2 on 2023-06-22 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telefone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída')], max_length=3)),
                ('mensagem', models.TextField()),
                ('telefone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telefone.telefone')),
            ],
        ),
    ]
