# Generated by Django 4.2.2 on 2023-06-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
