# Generated by Django 4.2.2 on 2023-06-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefone', '0002_rename_telefone_telefone_numero_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='chave_cadastro',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='telefone',
            name='endereco',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefone',
            name='escolaridade',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefone',
            name='idade_jovem',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefone',
            name='nome_jovem',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefone',
            name='nome_responsavel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefone',
            name='objetivo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefone',
            name='telefone_jovem',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telefone',
            name='telefone_responsavel',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
