# Generated by Django 4.2.2 on 2023-06-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefone', '0004_telefone_disponibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefone',
            name='endereco',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='escolaridade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='idade_jovem',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='nome_jovem',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='objetivo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='telefone_jovem',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='telefone_responsavel',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
