# Generated by Django 4.2.2 on 2023-06-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefone', '0005_alter_telefone_endereco_alter_telefone_escolaridade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='case',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='ordem',
            field=models.FloatField(),
        ),
    ]
