# Generated by Django 4.2.2 on 2023-06-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telefone', '0006_telefone_case_alter_telefone_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='apelido',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='telefone',
            name='turno',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
